### PR TITLE
Implemented Horizontal RecyclerView.

### PR DESCRIPTION
**Pull request by rafagcamargo**
- Upgrade to use latest build tools.
- Added recyclerview, picasso.
- Removed duplicate fileTree line.
- Renamed LoginActivity to TravelGuideActivity.
- Added basic structure to added fragments into TravelGuideActivity, by now we could use action bar to access our "in development" fragments. I've created two menu items called "LoginFragment" and "Trip Plan Fragment".
- Created DayAdapter.
- Created LoginFragment.
- Created TripPlanDetailsFragment.
- Renamed Day, Place and TripPlan removing ParseModel as suffix.
- Implemented Horizontal Recycler View.
- Created Rounded background for item day and selector as well.

### CODE REVIEW

**Comment by rafagcamargo** [comment]
@kprav @SharedMocha, guys take a look and merge before you start coding tomorrow to avoid conflicts. Everything i have done it's available on the description.

You don't need me to merge, feel free to do it.

Thanks! Talk to you tomorrow.

**Comment by kprav** [comment]
@rafagcamargo I am OK to merge. Can do once @SharedMocha confirms

**Comment by SharedMocha** [comment]
I am good too .Please go ahead with merge

Thanks,
Hemanth

**Comment by SharedMocha** [comment]
Good.
Lets have a call around 2..if everyone is ok

Thanks,
Hemanth

**Comment by kprav** [comment]
Nice, merged into my branch too. Thanks!

**Pull request merged**
